language: python
python:
  - "3.4"
  - "3.5"
os:
  - linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install unity -y
  - sudo apt-get install apache2 -y
  - sudo apt-get install php5 -y
install: true
before_script:
  - sudo cp -f test/travis-ci-apache /etc/apache2/sites-available/default
  - sudo service apache2 restart
script:
  - python test.py
notifications:
    email: false