language: python
python:
  - "3.4"
  - "3.5"
os:
  - linux
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install unity -y
install:
  - pip install tkinter
script:
  - python main.py
notifications:
    email: false